name: Genomics Standards
description: Submit a new genomics standard or update an existing standard for review.
labels: ["genomics", "review"]
assignees:
  - turukawa
  - lnanderson
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to contribute to this MOMSI genomics standard!
  - type: dropdown
    id: standard-type
    attributes:
      label: Standard Type
      description: What type of standard is it?
      options:
        - Reporting Guideline
        - Terminology Artefact
        - Model/Format
        - Identifier Schema
        - Multi-Standard Applicable
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the status of the standard?
      options:
        - Established
        - Established/Maintained
        - Depreciated
        - In Development
        - Obsolete
        - Uncertain
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Country
      description: What region or country is the standard organisation active in?
      placeholder: e.g. Worldwide
    validations:
      required: true
  - type: dropdown
    id: domain-class-subclass
    attributes:
      label: Domain Class/Subclass
      description: What is the domain class or -subclass of the standard most aligned?
      multiple: true
      options:
        - Genomics
        - Transcriptomics
        - Epigenomics
        - Genomics/Transcriptomics
        - Genomics/Transcriptomics/Epigenomics
        - Multi-omics Applicable
    validations:
      required: true
  - type: dropdown
    id: application-technology
    attributes:
      label: Application Technology
      description: What application technology applies to this standard?
      multiple: true
      options:
        - Sequencing (general)
        - High-Throughput Sequencing
        - DNA Sequencing
        - RNA Sequencing
        - Methylation Sequencing
        - Long-Read Sequencing
        - Array Sequencing
        - Other
    validations:
      required: true
  - type: input
    id: standard-name
    attributes:
      label: Standard Name
      description: What is the name of the standard?
      placeholder: e.g. Minimum Information about any (X) Sequence
    validations:
      required: true
  - type: input
    id: acronym-short-name
    attributes:
      label: Acronym/Short Name
      description: What is the standard's acronym?
      placeholder: e.g. MIxS
  - type: dropdown
    id: planning
    attributes:
      label: Planning
      description: What activity best describes the standard relationship to the [planning]](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Planning.md) stage of the research data lifecyce?
      options:
        - Experimental Design
        - Computed Analysis Design
        - All of the above
        - Uncertain
        - N/A
    validations:
      required: true
  - type: dropdown
    id: collection
    attributes:
      label: Collection
      description: What activity best describes the standard relationship to the [collection](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Collection.md) stage of the research data lifecyce?
      options:
        - Sample Preparation
        - Data Acquisition
        - All of the above
        - Uncertain
        - N/A
    validations:
      required: true
  - type: dropdown
    id: processing
    attributes:
      label: Processing
      description: What activity best describes the standard relationship to the [processing](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Processing.md) stage of the research data lifecyce?
      options:
        - Data Pre-Processing
        - Data Feature Detection/Identification
        - Data Normalization
        - Metadata Collection
        - All of the above
        - Uncertain
        - N/A
    validations:
      required: true
  - type: dropdown
    id: analysis
    attributes:
      label: Analysis
      description: What activity best describes the standard relationship to the [analysis](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Analysis.md) stage of the research data lifecyce?
      options:
        - Qualitative Analysis
        - Quantitative Analysis
        - Statistical Analysis
        - Interpretation Analysis
        - Software Specific
        - All of the above
        - Uncertain
        - Other
        - N/A
    validations:
      required: true
  - type: dropdown
    id: preservation
    attributes:
      label: Preservation
      description: What activity best describes the standard relationship to the [preservation](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Preservation.md) stage of the research data lifecyce?
      options:
        - Data (raw, processed, generated) Storage
        - Metadata Storage
        - All of the above
        - Uncertain
        - N/A
    validations:
      required: true
  - type: dropdown
    id: sharing
    attributes:
      label: Sharing
      description: What activity best describes the standard relationship to the [sharing](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Sharing.md) stage of the research data lifecyce?
      options:
        - Article (human-readable)
        - Knowledgebase (machine-readable)
        - Repository (machine-readable)
        - All of the above
        - Uncertain
        - Other
        - N/A
    validations:
      required: true
  - type: dropdown
    id: reuse
    attributes:
      label: Reuse
      description: What expert guidance best describes the standard relationship to the [reuse](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Reuse.md) stage of the research data lifecyce?
      options:
        - Required for Reuse
        - Recommended for Reuse
        - Not Required for Reuse
        - Conditional based on linked standards
        - Uncertain
        - Other
        - N/A
    validations:
      required: true
  - type: checkboxes
    id: meets-criteria
    attributes:
      label: Meets Criteria
      description: Does this standard [meet criteria](https://github.com/RDA-MOMSI/Dashboard/blob/main/src/glossary/Meets-Criteria.md) for the MOMSI minimum level of required information to be selected for the [MOMSI Standards Collection](https://fairsharing.org/5742)? 
      options:
        - label: Meets criteria for the MOMSI Standards Collection at FAIRsharing
  - type: input
    id: active-affiliations
    attributes:
      label: Active Affiliation(s)
      description: What organisation is the standard affiliated to?
      placeholder: e.g. Genome Standards Consortium (GSC)
    validations:
      required: true
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: What is the standard's homepage URL?
      placeholder: e.g. https://genomicsstandardsconsortium.github.io/mixs
    validations:
      required: true
  - type: input
    id: reference-article-citation-doi
    attributes:
      label: Reference Article Citation (DOI)
      description: Provide a DOI for any relevant journal article references?
      placeholder: e.g. https://doi.org/10.1038/nbt.1823
  - type: input
    id: reference-source-code-doi
    attributes:
      label: Reference Source Code (DOI or URL)
      description: Provide a URL or DOI for relevant references?
      placeholder: e.g. https://github.com/GenomicsStandardsConsortium/mixs
  - type: input
    id: fairsharing-record-doi
    attributes:
      label: FAIRsharing Record (DOI or URL)
      description: Provide a URL or DOI for relevant references?
      placeholder: e.g. https://doi.org/10.25504/FAIRsharing.9aa0zp
  - type: input
    id: contributor-name
    attributes:
      label: Contributor Name
      description: Provide your name for attribution as a contributor
      placeholder: e.g. Symona Adaro
  - type: input
    id: contributor-orcid-id
    attributes:
      label: Contributor ORCID ID
      description: Provide your ORCID ID?
      placeholder: e.g. 0000-0000-0000-0000
  - type: dropdown
    id: credit
    attributes:
      label: CRediT
      description: Select from the Contributor Role Taxonomy ([CRediT](https://credit.niso.org/)) options provided to describe your contributions.
      options:
        - "Data curation; Writing - review & editing"
        - "Data curation; Writing - original draft"
        - N/A
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: If you have any additional comments or questions about this issue request you'd like to provide, not covered in the above required fields, please leave them here.
